name: Update Google Fonts Database

# Cem Baspinar, 2025. MIT License

on:
  schedule:
    # Run monthly on the 1st at 2 AM UTC
    - cron: '0 2 1 * *'
  
  push:
    branches: [ main ]
    paths:
      - 'scripts/**'
      - '.github/workflows/**'
  
  workflow_dispatch:
    # Allow manual triggering
    inputs:
      force_rebuild:
        description: 'Force complete rebuild'
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  actions: read

jobs:
  update-database:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # 2 hours max
    
    steps:
      - name: Checkout GoogleFontsDB repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            fonttools \
            woff2 \
            python3-pil \
            python3-cairo \
            python3-gi \
            python3-gi-cairo \
            gir1.2-pango-1.0 \
            libcairo2-dev \
            pkg-config

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Clone Google Fonts repository
        run: |
          echo "Cloning Google Fonts repository..."
          git clone --depth 1 https://github.com/google/fonts.git google-fonts-source
          echo "Google Fonts repo cloned successfully"
          du -sh google-fonts-source/

      - name: Archive existing database
        run: |
          echo "Archiving existing database files..."
          python scripts/archive_database.py
          echo "Database archiving completed"

      - name: Generate font metadata database
        run: |
          echo "Starting font metadata extraction..."
          python scripts/generate_metadata.py
          echo "Metadata extraction completed"

      - name: Generate SVG font previews
        run: |
          echo "Starting SVG preview generation..."
          # Ensure no previews directory exists
          rm -rf previews/
          python scripts/generate_svg_previews.py
          # Remove any accidentally created preview files
          rm -rf previews/
          echo "SVG preview generation completed"

      - name: Optimize and compress database
        run: |
          echo "Optimizing database..."
          python scripts/optimize_database.py
          echo "Database optimization completed"

      - name: Generate statistics
        run: |
          python scripts/generate_stats.py

      - name: Generate changelog
        run: |
          echo "Generating changelog..."
          python scripts/generate_changelog.py
          echo "Changelog generation completed"

      - name: Validate generated files
        run: |
          echo "Validating generated files..."
          python scripts/validate_output.py
          echo "Validation completed"

      - name: Cleanup temporary files
        run: |
          rm -rf google-fonts-source/
          rm -rf temp/
          rm -rf previews/
          # Keep archives directory for historical versions
          echo "Cleanup completed (archives preserved)"

      - name: Check for changes
        id: check_changes
        run: |
          git add .
          git add archives/ 2>/dev/null || true  # Add archives if they exist
          if git diff --staged --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          else
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected"
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git config --global --add safe.directory /github/workspace
          
          # Get current date for commit message
          CURRENT_DATE=$(date -u +"%Y-%m-%d")
          
          # Count fonts in database
          FONT_COUNT=$(python -c "
          import json
          with open('font-database.json', 'r') as f:
              data = json.load(f)
              print(len(data.get('fonts', {})))
          ")
          
          git commit -m "Update font database - ${CURRENT_DATE}

          - Updated font database with ${FONT_COUNT} font families
          - Generated SVG previews and metadata
          - Automated update via GitHub Actions
          
          Database version: $(date -u +"%Y.%m.%d")"
          
          git push

      - name: Create release
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          # Generate release tag and name
          RELEASE_TAG="v$(date -u +"%Y.%m.%d")"
          RELEASE_NAME="Font Database $(date -u +"%Y.%m.%d")"
          RELEASE_DATE="$(date -u +"%Y-%m-%d %H:%M:%S UTC")"
          
          # Get font count from database
          FONT_COUNT=$(python -c "
          import json
          with open('font-database.json', 'r') as f:
              data = json.load(f)
              print(len(data.get('fonts', {})))
          ")
          
          # Get database size
          DB_SIZE=$(du -h font-database.json | cut -f1)
          
          # Read changelog content
          CHANGELOG_CONTENT=""
          if [ -f "release-changelog.md" ]; then
            CHANGELOG_CONTENT=$(cat release-changelog.md)
          fi
          
          # Create release using GitHub CLI
          gh release create "$RELEASE_TAG" \
            --title "$RELEASE_NAME" \
            --notes "# Automated Google Fonts Database Update

          📊 **Statistics:**
          - Total font families: $FONT_COUNT
          - Database size: $DB_SIZE
          - Generated: $RELEASE_DATE

          $CHANGELOG_CONTENT

          ---

          📦 **Files:**
          - \`font-database.json\` - Complete database
          - \`font-database.json.gz\` - Compressed version  
          - \`font-families-index.json\` - Family names index
          - \`font-categories-index.json\` - Category index
          - \`font-popular-index.json\` - Popular fonts index
          - \`stats.json\` - Database statistics
          - \`checksums.json\` - File integrity checksums

          🔄 **Processing:**
          - Updated font metadata from Google Fonts repository
          - Generated compressed SVG previews (~800KB total)
          - Applied database optimization and deduplication
          - Created specialized index files for different use cases" \
            font-database.json \
            font-database-optimized.json \
            font-database.json.gz \
            font-families-index.json \
            font-categories-index.json \
            font-popular-index.json \
            stats.json \
            checksums.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload database artifacts
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          ARTIFACT_NAME="font-database-$(date -u +"%Y%m%d")"
          echo "Creating artifact: $ARTIFACT_NAME"
        
      - name: Upload artifacts
        if: steps.check_changes.outputs.changes == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: font-database-${{ github.run_number }}
          path: |
            font-database.json
            font-database-optimized.json
            font-database.json.gz
            font-families-index.json
            font-categories-index.json
            font-popular-index.json
            stats.json
            checksums.json
            CHANGELOG.md
            release-changelog.md
          retention-days: 30
          compression-level: 9
          if-no-files-found: warn

      - name: Post-update summary
        if: always()
        run: |
          echo "=== Font Database Update Summary ==="
          echo "Status: ${{ job.status }}"
          echo "Changes detected: ${{ steps.check_changes.outputs.changes }}"
          echo "Timestamp: $(date -u)"
          
          if [ -f "stats.json" ]; then
            echo "=== Statistics ==="
            cat stats.json
          fi
          
          echo "=== File sizes ==="
          if [ -f "font-database.json" ]; then
            echo "Database: $(du -h font-database.json | cut -f1)"
          fi
          if [ -f "font-database.json.gz" ]; then
            echo "Compressed: $(du -h font-database.json.gz | cut -f1)"
          fi